# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/tmp/h2db
    username: sa
    password: sa
  sql:
    init:
      schema-locations: classpath:sql-script/h2/schema.sql
#      data-locations: classpath:sql-script/h2/data.sql
  h2:
    console:
      enabled: true
